### ISSUE TITLE
Grabbing the scroll bar and moving the mouse up causes the  "currently playing track" to disappear

### ISSUE THREAD

**Issue by f3ndot** [PlugForMac/Plug2Issues#103]
![lost-sticky-player](https://cloud.githubusercontent.com/assets/740289/11689257/0fe923b8-9e5f-11e5-881d-d6d491551424.gif)

**Comment by alexmarchant** [comment]
Thanks @f3ndot.

Looks like this only happens when clicking and holding the scroll bar and moving it up and down. Pretty sure this is because the scroll bar jumps up as the sticky track hides, then jumps back down because the mouse is still attached to it. Must cause the scroll view to move up/down faster than we are detecting.

**Comment by alexmarchant** [comment]
PS @f3ndot what do you use to screen capture gifs?

**Comment by f3ndot** [comment]
@alexmarchant the amazing [LICEcap](http://www.cockos.com/licecap/)! Simple, but quite powerful

**Comment by alexmarchant** [comment]
@f3ndot just tested it out, simple, works great, thanks!
