### ISSUE TITLE
Trackview insets jump with sticky track

### ISSUE THREAD

**Issue by finder39** [PlugForMac/Plug2Issues#135]
![insets jump](https://cloud.githubusercontent.com/assets/518673/16530294/499cbfe8-3f7c-11e6-91b5-2df6a495f324.gif)

**Comment by alexmarchant** [comment]
Ya, that was intentional, but it has caused some problems. Most notably when you click and hold on the scroll bar and move the mouse up and down, it really wreaks havoc on sticky track placement.

The rationale behind this decision was that since the sticky track is on top of the table view/scroll view, the scroll bar would fall behind the sticky track and was obscured. This looked strange. I spent some time trying to pin the sticky track inside the scroll view but didn't have much luck. Maybe that is still the route to go and we just need to spend more time making that work. Or maybe having the scroll bar behind the sticky track is NBD.

**Comment by finder39** [comment]
Hmm I get what you mean. We could work on having the stick track being behind the scroll bar, I'll look at it at some point. Just logging it for now :)
